title: PortalZ Website
author:
  name: Zachary Yaro
  url: https://zmyaro.com

gh_img_url: "https://raw.githubusercontent.com/ZMYaro/portalz/master/images/"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "downloads"
    values:
      section: "downloads"
  -
    scope:
      path: "media"
    values:
      section: "media"
  -
    scope:
      path: "commentary"
    values:
      section: "commentary"
